### ISSUE TITLE
milestone#0 - 공통 제작 (공통 모달 제작)

### ISSUE THREAD

**Issue by TomHoon** [TomHoon/OliveYoung_Frontend#11]
## 작업내용
- 공통 모달 제작

## 마감일
- 2023-09-23

## 하위테스크
- 공통 모달 제작

## 참고사항
- 'ModalWrapper'라는 이름의 공통 컴포넌트 제작
- 딤처리 여부를 props로 받을 수 있게 제작
- ModalWrapper내에 slot을 통해 어떤 내용이 들어와도 재사용 가능하도록 하기
- 모달은 둥굴고 딤 부분은 흐리게 제작

**Comment by euntaek419** [comment]
작업완료
